BookiFy/Controllers/OrderController.cs
using BookiFy.Data.Interfaces;
using BookiFy.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookiFy.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;
        public OrderController(IOrderRepository orderRepository, ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }
        public IActionResult CheckOut()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CheckOut(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your card is empty, add some drinks first");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckOutComplete");
            }

            return View(order);
        }
        [HttpPost]
        public IActionResult CheckOutComplete()
        {
            ViewBag.CheckOutMessage = "Thanks For The Order";
            return View();
        }
    }
}

BookiFy/Controllers/ShoppingCartController.cs
using BookiFy.Data.Interfaces;
using BookiFy.Data.Models;
using BookiFy.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookiFy.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IItemRepository _itemRepository;
        private readonly ShoppingCart _shoppingCart;
        public ShoppingCartController(IItemRepository itemRepository, ShoppingCart shoppingCart)
        {
            _itemRepository = itemRepository;
            _shoppingCart = shoppingCart;
        }
        public IActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var sCVM = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = (double)_shoppingCart.GetShoppingCartTotal()

            };
            return View(sCVM);
        }
        public RedirectToActionResult AddToShoppingCart(int itemID)
        {
            var selectedItem = _itemRepository.Items.FirstOrDefault(p => p.ItemId == itemID);
            if (selectedItem != null)
            {
                _shoppingCart.AddToCart(selectedItem, 1);

            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult RemoveFromShoppingCart(int itemId)
        {
            var selectedItem = _itemRepository.Items.FirstOrDefault(p => p.ItemId == itemId);
            if (selectedItem != null)
            {
                _shoppingCart.RemoveFromCart(selectedItem, 1);

            }
            return RedirectToAction("Index");
        }
    }
}

BookiFy/Views/ShoppingCart/Index.cshtml
@{
    @using BookiFy.ViewModel;
    @model ShoppingCartViewModel
}
<div class="row checkoutForm">
    <h2>Your shopping cart</h2>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Item</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left">@line.Item.ItemName</td>
                    <td class="text-right">@line.Item.Price.ToString("c")</td>
                    <td class="text-right">
                        @((line.Amount * line.Item.Price).ToString("c"))
                    </td>
                    <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-itemId="@line.Item.ItemId">Remove</a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.ShoppingCartTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
            <a class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Add more items<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a asp-controller="Item" asp-action="List" asp-route-category="Used">USED</a></li>
                    <li><a asp-controller="Item" asp-action="List" asp-route-category="New">NEW</a></li>
                </ul>
            </a>
        </div>
    </div>
</div>